# Project Sentinel -- API service (FastAPI + core/agent/ingest).
# Multi-stage: build the venv with uv, then copy only the venv + source
# into a slim runtime image. Reads only data/reference/ and
# data/snapshots/ at runtime (both committed to git, no volume needed
# for the default demo path) -- matches README's "no network required"
# claim; the one exception is POST /api/ask, which needs an LLM key.

FROM python:3.12-slim AS builder

# CBC (pulp's LP solver) ships prebuilt in the pulp wheel for linux/amd64
# and linux/arm64 -- no system solver package needed. build-essential
# covers the rare source-build fallback for a dependency without a wheel
# for this platform.
RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
    && rm -rf /var/lib/apt/lists/*

# `latest` rather than a pinned patch version: this environment has no
# Docker access to verify a specific tag actually exists in the registry
# right now. Pin to a specific version (e.g. matching `uv --version` on
# your machine, 0.11.x as of this build) once you've confirmed it pulls.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

WORKDIR /app
COPY pyproject.toml uv.lock ./
# --no-install-project: cache the dependency layer separately from app
# code, so editing core/*.py doesn't invalidate the (slow) dependency sync
RUN uv sync --frozen --no-install-project --no-dev

COPY . .
RUN uv sync --frozen --no-dev


FROM python:3.12-slim AS runtime

RUN groupadd -r sentinel && useradd -r -g sentinel sentinel

WORKDIR /app
COPY --from=builder /app /app
ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    API_HOST=0.0.0.0

# data/raw/ is gitignored (large PDFs/duckdb, regenerated by ingest/) --
# create it so a re-ingestion run inside the container has somewhere to
# write without needing root.
RUN mkdir -p data/raw && chown -R sentinel:sentinel /app

USER sentinel

EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/api/health', timeout=3)" || exit 1

CMD ["python", "api/main.py"]
